protect main & develop branches localy

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,21 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Protect master from accidental commits.
+echo -e "===\n>> Checking branch name"
+branchName=$(git branch | grep '*' | sed 's/* //')
+echo $branchName
+if [ $branchName == 'main' ]
+then
+  echo -e "\n🚫 Commit directly to master branch is not allowed!\n" && exit 1
+fi
+
+if [ $branchName == 'develop' ]
+then
+  echo -e "\n🚫 Cannot commit to remote develop branch, please create your own branch with develop/branch-name format" && exit 1
+fi
+
+echo -e ">> Finish checking branch name.\n==="
+
 npm run lint
 npm run test
